--liquibase formatted sql

--changeset alex:1
CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname  VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL UNIQUE,
    birth_day   DATE,
    CONSTRAINT pk_users_id PRIMARY KEY (id)
    );
--rollback DROP TABLE users;

--changeset alex:2
CREATE TABLE users_roles(
 user_id BIGINT,
 name VARCHAR(250) NOT NULL,
 CONSTRAINT pk_user_id_name PRIMARY KEY (user_id,name),
 CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
--rollback DROP TABLE users_roles;

--changeset alex:3
CREATE TABLE IF NOT EXISTS specification(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code VARCHAR(255) NOT NULL,
  amount INT NOT NULL,
  description VARCHAR(255),
  user_id BIGINT NOT NULL,
 CONSTRAINT pk_specification_id PRIMARY KEY (id),
 CONSTRAINT uq_specification_code UNIQUE (code),
 CONSTRAINT fk_specification_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );
--rollback DROP TABLE specification;

--changeset alex:4
CREATE TABLE IF NOT EXISTS detail(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255),
amount INT NOT NULL,
specification_id BIGINT NOT NULL,
CONSTRAINT fk_detail_specification FOREIGN KEY (specification_id) REFERENCES specification(id) ON DELETE CASCADE,
CONSTRAINT pk_detail_id PRIMARY KEY (id)
);
--rollback DROP TABLE detail;