spring:
  datasource:
    password: root
    username: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6532/root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: **************
            client-secret: **************
            scope: openid,profile,email
            redirect-uri: http://localhost:8085/login/oauth2/code/google
  liquibase:
    contexts: dev
server:
  port: 8085

logging:
  file:
    path: /
    name: logg.log
  level:
    root: INFO
